const CREATE = 'CREATE'
const UPDATE = 'UPDATE'
const DELETE = 'DELETE'
const FETCH_ALL = 'FETCH_ALL'
const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH'
const START_LOADING = 'START_LOADING'
const STOP_LOADING = 'STOP_LOADING'
const AUTH = 'AUTH'
const LOGOUT = 'LOGOUT'
const LIKE = 'LIKE'
const FETCH_POST = 'FETCH_POST'
const COMMENT = 'COMMENT'

export {
  CREATE,
  START_LOADING,
  STOP_LOADING,
  UPDATE,
  DELETE,
  FETCH_ALL,
  LOGOUT,
  AUTH,
  FETCH_BY_SEARCH,
  LIKE,
  FETCH_POST,
  COMMENT,
}
